"""
Constantes partagées : paniers d'actions par marché. Aucune dépendance sur
les autres modules du projet.
"""

# Composition approximative du CAC 40 (tickers Yahoo Finance, suffixe .PA/.AS).
# Maintenue à la main : la composition officielle change de temps en temps,
# ajuster ce dict si besoin (ajout/retrait d'une valeur, ticker erroné...).
CAC40_TICKERS = {
    "Air Liquide": "AI.PA",
    "Airbus": "AIR.PA",
    "ArcelorMittal": "MT.AS",
    "Axa": "CS.PA",
    "BNP Paribas": "BNP.PA",
    "Bouygues": "EN.PA",
    "Capgemini": "CAP.PA",
    "Carrefour": "CA.PA",
    "Crédit Agricole": "ACA.PA",
    "Danone": "BN.PA",
    "Dassault Systèmes": "DSY.PA",
    "Edenred": "EDEN.PA",
    "Engie": "ENGI.PA",
    "EssilorLuxottica": "EL.PA",
    "Eurofins Scientific": "ERF.PA",
    "Hermès": "RMS.PA",
    "Kering": "KER.PA",
    "L'Oréal": "OR.PA",
    "Legrand": "LR.PA",
    "LVMH": "MC.PA",
    "Michelin": "ML.PA",
    "Orange": "ORA.PA",
    "Pernod Ricard": "RI.PA",
    "Publicis": "PUB.PA",
    "Renault": "RNO.PA",
    "Safran": "SAF.PA",
    "Saint-Gobain": "SGO.PA",
    "Sanofi": "SAN.PA",
    "Schneider Electric": "SU.PA",
    "Société Générale": "GLE.PA",
    "Stellantis": "STLAP.PA",
    "STMicroelectronics": "STMPA.PA",
    "Teleperformance": "TEP.PA",
    "Thales": "HO.PA",
    "TotalEnergies": "TTE.PA",
    "Unibail-Rodamco-Westfield": "URW.PA",
    "Veolia": "VIE.PA",
    "Vinci": "DG.PA",
    "Vivendi": "VIV.PA",
    "Worldline": "WLN.PA",
}

# Sélection de grandes capitalisations allemandes (DAX 40, tickers Xetra ".DE").
DAX40_TICKERS = {
    "Adidas": "ADS.DE",
    "Airbus (Francfort)": "AIR.DE",
    "Allianz": "ALV.DE",
    "BASF": "BAS.DE",
    "Bayer": "BAYN.DE",
    "Beiersdorf": "BEI.DE",
    "BMW": "BMW.DE",
    "Brenntag": "BNR.DE",
    "Commerzbank": "CBK.DE",
    "Continental": "CON.DE",
    "Covestro": "1COV.DE",
    "Daimler Truck": "DTG.DE",
    "Deutsche Bank": "DBK.DE",
    "Deutsche Börse": "DB1.DE",
    "DHL Group": "DHL.DE",
    "Deutsche Telekom": "DTE.DE",
    "E.ON": "EOAN.DE",
    "Fresenius": "FRE.DE",
    "Fresenius Medical Care": "FME.DE",
    "Hannover Rück": "HNR1.DE",
    "Heidelberg Materials": "HEI.DE",
    "Henkel": "HEN3.DE",
    "Infineon": "IFX.DE",
    "Mercedes-Benz Group": "MBG.DE",
    "Merck KGaA": "MRK.DE",
    "MTU Aero Engines": "MTX.DE",
    "Munich Re": "MUV2.DE",
    "Porsche AG": "P911.DE",
    "Porsche SE": "PAH3.DE",
    "Qiagen": "QIA.DE",
    "Rheinmetall": "RHM.DE",
    "RWE": "RWE.DE",
    "SAP": "SAP.DE",
    "Sartorius": "SRT3.DE",
    "Siemens": "SIE.DE",
    "Siemens Energy": "ENR.DE",
    "Siemens Healthineers": "SHL.DE",
    "Symrise": "SY1.DE",
    "Volkswagen": "VOW3.DE",
    "Vonovia": "VNA.DE",
    "Zalando": "ZAL.DE",
}

# Sélection de grandes capitalisations britanniques (proche du FTSE 100, tickers Londres ".L").
FTSE100_TICKERS = {
    "AstraZeneca": "AZN.L",
    "Shell": "SHEL.L",
    "HSBC Holdings": "HSBA.L",
    "Unilever": "ULVR.L",
    "BP": "BP.L",
    "Rio Tinto": "RIO.L",
    "Diageo": "DGE.L",
    "GSK": "GSK.L",
    "British American Tobacco": "BATS.L",
    "Glencore": "GLEN.L",
    "RELX": "REL.L",
    "National Grid": "NG.L",
    "Lloyds Banking Group": "LLOY.L",
    "BAE Systems": "BA.L",
    "Barclays": "BARC.L",
    "Compass Group": "CPG.L",
    "Rolls-Royce Holdings": "RR.L",
    "Reckitt Benckiser": "RKT.L",
    "Vodafone Group": "VOD.L",
    "Prudential": "PRU.L",
    "Anglo American": "AAL.L",
    "Tesco": "TSCO.L",
    "Aviva": "AV.L",
    "Legal & General": "LGEN.L",
    "Standard Chartered": "STAN.L",
    "Next": "NXT.L",
    "Sage Group": "SGE.L",
    "Whitbread": "WTB.L",
    "Persimmon": "PSN.L",
    "Rentokil Initial": "RTO.L",
    "InterContinental Hotels": "IHG.L",
    "3i Group": "III.L",
    "Antofagasta": "ANTO.L",
    "Croda International": "CRDA.L",
    "Imperial Brands": "IMB.L",
    "Melrose Industries": "MRO.L",
    "Pearson": "PSON.L",
    "SSE": "SSE.L",
    "Segro": "SGRO.L",
    "Smith & Nephew": "SN.L",
    "Associated British Foods": "ABF.L",
    "Auto Trader Group": "AUTO.L",
    "BT Group": "BT-A.L",
    "DCC": "DCC.L",
    "Diploma": "DPLM.L",
    "Entain": "ENT.L",
    "Experian": "EXPN.L",
    "Fresnillo": "FRES.L",
    "Haleon": "HLN.L",
    "Halma": "HLMA.L",
    "International Consolidated Airlines Group": "IAG.L",
    "Intertek Group": "ITRK.L",
    "JD Sports Fashion": "JD.L",
    "Kingfisher": "KGF.L",
    "London Stock Exchange Group": "LSEG.L",
    "M&G": "MNG.L",
    "Marks & Spencer": "MKS.L",
    "Mondi": "MNDI.L",
    "NatWest Group": "NWG.L",
    "Rightmove": "RMV.L",
    "J Sainsbury": "SBRY.L",
    "Schroders": "SDR.L",
    "Severn Trent": "SVT.L",
    "Smiths Group": "SMIN.L",
    "Spirax Group": "SPX.L",
    "St James's Place": "STJ.L",
    "Taylor Wimpey": "TW.L",
    "United Utilities Group": "UU.L",
    "Weir Group": "WEIR.L",
    "WPP": "WPP.L",
}

# Sélection de grandes capitalisations américaines (pas le S&P 500 complet, 500
# tickers rendraient le chargement beaucoup trop long, mais un échantillon large
# et diversifié par secteur).
US_TICKERS = {
    "Apple": "AAPL",
    "Microsoft": "MSFT",
    "Alphabet (Google)": "GOOGL",
    "Amazon": "AMZN",
    "NVIDIA": "NVDA",
    "Meta Platforms": "META",
    "Tesla": "TSLA",
    "Berkshire Hathaway": "BRK-B",
    "JPMorgan Chase": "JPM",
    "Visa": "V",
    "Johnson & Johnson": "JNJ",
    "Walmart": "WMT",
    "Mastercard": "MA",
    "Procter & Gamble": "PG",
    "Exxon Mobil": "XOM",
    "UnitedHealth Group": "UNH",
    "Home Depot": "HD",
    "Chevron": "CVX",
    "Merck & Co": "MRK",
    "Eli Lilly": "LLY",
    "AbbVie": "ABBV",
    "Coca-Cola": "KO",
    "PepsiCo": "PEP",
    "Costco": "COST",
    "Bank of America": "BAC",
    "McDonald's": "MCD",
    "Adobe": "ADBE",
    "Netflix": "NFLX",
    "Broadcom": "AVGO",
    "Salesforce": "CRM",
    "Walt Disney": "DIS",
    "Nike": "NKE",
    "Intel": "INTC",
    "Cisco Systems": "CSCO",
    "Verizon": "VZ",
    "AT&T": "T",
    "Pfizer": "PFE",
    "Comcast": "CMCSA",
    "Oracle": "ORCL",
    "IBM": "IBM",
    "Abbott Laboratories": "ABT",
    "Thermo Fisher Scientific": "TMO",
    "Linde": "LIN",
    "Texas Instruments": "TXN",
    "Qualcomm": "QCOM",
    "Honeywell": "HON",
    "Union Pacific": "UNP",
    "Danaher": "DHR",
    "American Express": "AXP",
    "Goldman Sachs": "GS",
    "Morgan Stanley": "MS",
    "Caterpillar": "CAT",
    "Boeing": "BA",
    "3M": "MMM",
    "Starbucks": "SBUX",
    "Lowe's": "LOW",
    "Booking Holdings": "BKNG",
    "PayPal": "PYPL",
    "ServiceNow": "NOW",
    "Intuit": "INTU",
    "Advanced Micro Devices": "AMD",
    "Lockheed Martin": "LMT",
    "Philip Morris International": "PM",
    "Altria Group": "MO",
    "Colgate-Palmolive": "CL",
    "CVS Health": "CVS",
    "T-Mobile US": "TMUS",
    "Charles Schwab": "SCHW",
    "Blackstone": "BX",
    "GE Aerospace": "GE",
}

# Sélection de grandes capitalisations néerlandaises (AEX, Euronext Amsterdam, tickers ".AS").
# Éligible PEA (UE/EEE) comme CAC 40 et DAX 40, contrairement au FTSE 100 et aux actions US.
AEX_TICKERS = {
    "ASML Holding": "ASML.AS",
    "Heineken": "HEIA.AS",
    "ING Groep": "INGA.AS",
    "Koninklijke Philips": "PHIA.AS",
    "Ahold Delhaize": "AD.AS",
    "Adyen": "ADYEN.AS",
    "Prosus": "PRX.AS",
    "Wolters Kluwer": "WKL.AS",
    "DSM-Firmenich": "DSFIR.AS",
    "Randstad": "RAND.AS",
    "Koninklijke KPN": "KPN.AS",
    "NN Group": "NN.AS",
    "ASM International": "ASM.AS",
    "Akzo Nobel": "AKZA.AS",
    "Aegon": "AGN.AS",
    "Signify": "LIGHT.AS",
    "IMCD": "IMCD.AS",
    "Exor": "EXO.AS",
    "Universal Music Group": "UMG.AS",
    "Euronext": "ENX.PA",
    "ABN AMRO Bank": "ABN.AS",
    "BE Semiconductor Industries": "BESI.AS",
}

# Sélection de grandes capitalisations espagnoles (IBEX 35, tickers Bourse de Madrid ".MC").
# Éligible PEA (UE/EEE).
IBEX35_TICKERS = {
    "Banco Santander": "SAN.MC",
    "BBVA": "BBVA.MC",
    "Iberdrola": "IBE.MC",
    "Inditex": "ITX.MC",
    "Repsol": "REP.MC",
    "Telefonica": "TEF.MC",
    "CaixaBank": "CABK.MC",
    "Naturgy Energy": "NTGY.MC",
    "Amadeus IT Group": "AMS.MC",
    "ACS": "ACS.MC",
    "Aena": "AENA.MC",
    "Grifols": "GRF.MC",
    "Mapfre": "MAP.MC",
    "Endesa": "ELE.MC",
    "Bankinter": "BKT.MC",
    "Banco de Sabadell": "SAB.MC",
    "Acciona": "ANA.MC",
    "Acerinox": "ACX.MC",
    "Enagas": "ENG.MC",
    "Redeia": "RED.MC",
    "Indra Sistemas": "IDR.MC",
    "Fluidra": "FDR.MC",
    "Inmobiliaria Colonial": "COL.MC",
    "Logista": "LOG.MC",
    "Puig Brands": "PUIG.MC",
    "Unicaja Banco": "UNI.MC",
    "Solaria Energia": "SLR.MC",
    "Laboratorios Rovi": "ROVI.MC",
}

# Sélection de grandes capitalisations italiennes (FTSE MIB, tickers Borsa Italiana ".MI").
# Éligible PEA (UE/EEE). CNH Industrial délistée de Milan (désormais NYSE uniquement) : exclue
# pour ne pas confondre avec Iveco Group, sa scission toujours cotée à Milan, déjà listée.
FTSEMIB_TICKERS = {
    "Enel": "ENEL.MI",
    "Eni": "ENI.MI",
    "Intesa Sanpaolo": "ISP.MI",
    "UniCredit": "UCG.MI",
    "Ferrari": "RACE.MI",
    "Assicurazioni Generali": "G.MI",
    "Telecom Italia": "TIT.MI",
    "Terna": "TRN.MI",
    "Snam": "SRG.MI",
    "Moncler": "MONC.MI",
    "Prysmian": "PRY.MI",
    "Mediobanca": "MB.MI",
    "Banco BPM": "BAMI.MI",
    "Leonardo": "LDO.MI",
    "Pirelli": "PIRC.MI",
    "Poste Italiane": "PST.MI",
    "Davide Campari-Milano": "CPR.MI",
    "Recordati": "REC.MI",
    "Amplifon": "AMP.MI",
    "Inwit": "INW.MI",
    "Italgas": "IG.MI",
    "Nexi": "NEXI.MI",
    "Iveco Group": "IVG.MI",
    "Tenaris": "TEN.MI",
    "DiaSorin": "DIA.MI",
    "Banca Mediolanum": "BMED.MI",
    "Hera": "HER.MI",
    "A2A": "A2A.MI",
    "BPER Banca": "BPE.MI",
}

# Les 20 valeurs du SMI suisse (tickers SIX Swiss Exchange ".SW"). PAS éligible PEA (Suisse hors
# UE/EEE, comme le Royaume-Uni et les États-Unis) : relève d'un compte-titres ordinaire (CTO).
SMI_TICKERS = {
    "Nestle": "NESN.SW",
    "Novartis": "NOVN.SW",
    "Roche Holding": "RO.SW",
    "UBS Group": "UBSG.SW",
    "ABB": "ABBN.SW",
    "Zurich Insurance Group": "ZURN.SW",
    "Richemont": "CFR.SW",
    "Holcim": "HOLN.SW",
    "Swiss Re": "SREN.SW",
    "Swisscom": "SCMN.SW",
    "Lonza Group": "LONN.SW",
    "Sika": "SIKA.SW",
    "Givaudan": "GIVN.SW",
    "Partners Group": "PGHN.SW",
    "Geberit": "GEBN.SW",
    "Logitech International": "LOGN.SW",
    "Kuehne + Nagel International": "KNIN.SW",
    "Sonova Holding": "SOON.SW",
    "Swiss Life Holding": "SLHN.SW",
    "Alcon": "ALC.SW",
}

UNIVERSE_CODES = ["cac40", "dax40", "ftse100", "us", "aex", "ibex35", "ftsemib", "smi"]
UNIVERSE_TICKERS = {
    "cac40": CAC40_TICKERS,
    "dax40": DAX40_TICKERS,
    "ftse100": FTSE100_TICKERS,
    "us": US_TICKERS,
    "aex": AEX_TICKERS,
    "ibex35": IBEX35_TICKERS,
    "ftsemib": FTSEMIB_TICKERS,
    "smi": SMI_TICKERS,
}
